spring:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/testcontainer
spring.datasource.username: root
spring.datasource.password: root